previewsEnabled: true
services:
  - type: web
    plan: free
    name: app
    env: python
    startCommand: "uvicorn main:ap --host 0.0.0.0 --port 8001 --reload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17