previewsEnabled: true
services:
  - type: web
    plan: standard
    name: app
    env: python
    startCommand: "uvicorn main:ap --host 0.0.0.0 --port 8001 --reload"
    envVars:
      - key: PYTHON_VERSION
        value: 3.8.17
      - key: my_env
        value: 27bed0121b936f977122d02fa7a45c7d